### ISSUE TITLE
Feature request: importing zipped files

### ISSUE THREAD

**Issue by LauHypershop** [LBannenberg/laravel-mysqldump#1]
Right now you have to unzip files before importing, OR rely on the command first trying to find dump.sql and then trying to find dump.sql.gz.

It would be better if the command always required a filename, but accepted either a .sql or .sql.gz and handled it accordingly.

**Comment by LauHypershop** [comment]
* Also, if it unzips to a temporary file, that file should be cleaned up after import. Whereas the original zipped file should be retained.
* Also, the "It is done" exit message should be improved, right now it looks like it refers to the unzipping being done, not the import being done.

**Comment by LBannenberg** [comment]
Resolved by https://github.com/LBannenberg/laravel-mysqldump/releases/tag/v2.0.0
